### ISSUE TITLE
Bluetooth Data

### ISSUE THREAD

**Issue by kprinssu** [icyleaf/anne-keyboard#1]
I am currently writing a C# based Windows 8/10 app that will control the backlights on the Anne Pro. Will you possibly open up the Bluetooth Low Energy protocol and packets that are being sent?

**Comment by icyleaf** [comment]
sorry, i am a user too. you can ask the creater in QQ group: 340574284 and find the man named " 司马狂徒" who is in charge of the technology(and the founder) of anne keyboard.

**Comment by kprinssu** [comment]
I have created an open source implementation of the Anne Pro keyboard's Bluetooth protocol here, https://github.com/kprinssu/anne-keyboard-windows
