### ISSUE TITLE
移动应用源代码 / Mobile app source code

### ISSUE THREAD

**Issue by josecostamartins** [icyleaf/anne-keyboard#2]
对不起写作不好，我不是中国人

你能发布移动应用程序的源代码吗？

谢谢

Sorry for the bad writing, I'm not Chinese

Could you guys release the source code for mobile applications? 

Thank you

**Comment by icyleaf** [comment]
sorry, i am a user too. you can ask the creater in QQ group: 340574284 and find the man named " 司马狂徒" who is in charge of the technology(and the founder) of anne keyboard.

**Comment by josecostamartins** [comment]
Thank you!
